### ISSUE TITLE
population 2020 & 2021

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality#101]
We had a chat with Akis about some aspects of excess mortality calculations 
He had an idea that the pops from 2020 that is already affected by pandemic shouldn't be used as is.
Rather - some interpolation of values, perhaps also from last 5 years should be used.
In order to get population counts assuming that pandemic didnt happen and the trends continued from earlier years.
That of course could be performed for each stratum separately.

**Comment by RPanczak** [comment]
Here are the new pops 
Data until 2021 are now in HMD fro CHE and SWE; old sources from INE for 2020-21 for ESP

![image](https://user-images.githubusercontent.com/31648642/140380641-778e966c-4a13-4567-9677-3f8cd7079ccd.png)

**Comment by jriou** [comment]
So the choice is between this one and a projection for 2021 from the 5 preceding years right?

I guess this looks reasonable, but at the same time the true counter factual would probably be to predict population in 2021 from 2015-2019. I would tend to use this last option. What do the others think?

**Comment by RPanczak** [comment]
Thanks. Will have a quick look how simple linear trend iterpolation of 2020 & 2021 would look like when using 2015-19 data.

@kasparstaub? @marcelzwahlen?

**Comment by RPanczak** [comment]
Here differences using data already aggregated in age groups. Simple lm or poisson model.
Should that be better done on 1 year age bands first and then aggregated to age bins?

![image](https://user-images.githubusercontent.com/31648642/140777939-8c74f3ef-d5e3-4b1d-acda-40626c7d690e.png)

**Comment by marcelzwahlen** [comment]
I would go with 5-year age groups. Linear Model should do the job.  I do not think we need to be more "sophisticated".

**Comment by RPanczak** [comment]
Thanks! Doesn't always work that well 🤒 

![image](https://user-images.githubusercontent.com/31648642/140793275-9fc82604-14ed-4e9e-ab4b-d59ab3681b2b.png)

**Comment by RPanczak** [comment]
`lm` has a bit of troubles with 'bends'
maybe polynomial would help a bit? 

here example from CH

![image](https://user-images.githubusercontent.com/31648642/140919027-d13c6519-c78f-475c-8c59-4305f5b0cb4f.png)

**Comment by jriou** [comment]
I would rather use splines than polynomials for extrapolation, but I guess for 1 or 2 years in the future it doesn't change much.

**Comment by RPanczak** [comment]
put the splines 
but it generates quite drama on the `warnings()` side
can you have a look @jriou plz?

![image](https://user-images.githubusercontent.com/31648642/140940522-37e0d4b0-03db-4ef8-b30a-6100fd18ea1d.png)

**Comment by jriou** [comment]
On it, I'm not so worried about the warnings since the fits look good. But the HMD data looks very strange in some instances, isn't it? What's happening for 40-49 in Sweden for instance?

![image](https://user-images.githubusercontent.com/16086845/140947125-88228f3a-19bb-459e-8fb9-74ff5569caa1.png)

**Comment by RPanczak** [comment]
Data came by email so who knows what happened in 🇸🇪 😟 

![image](https://user-images.githubusercontent.com/31648642/140948032-c107d952-d9f4-47be-a031-0c16c78ebd6b.png)
