### ISSUE TITLE
CmdStanR as engine

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality#102]
To replace `rstan` dramas?

Resources
https://mc-stan.org/cmdstanr/index.html

**Comment by jriou** [comment]
Yes that would be a solution, rather cmdstanr than pure cmdstan, but it's a
bit annoying to implement...

Le mar. 16 nov. 2021 à 09:36, Radoslaw Panczak ***@***.***> a
écrit :
