### ISSUE TITLE
Spain 2021

### ISSUE THREAD

**Issue by jriou** [RPanczak/ISPM_excess-mortality#103]
There is a problem with deaths by age in 2021. I added a temporary fix on 23_file, and launched the thing again on Ubelix. I will push the results tomorrow before, you'll just have to run Spain 2021 manually!

**Comment by RPanczak** [comment]
Thanks Julien 💪 
There was wrong variable name and wrong aggregation after data update 😵‍💫 
Should be fixed now 👾
