### ISSUE TITLE
Metrics for data quality

### ISSUE THREAD

**Issue by kasparstaub** [RPanczak/ISPM_excess-mortality#104]
Dear All, 

we have two comments referring to data quality, especially in the older data:

[A4] 4. Paragraph starting in line 89: Please provide more information about the datasets used including inconsistencies/limitations over time and across countries; include basic information about what data was collected and how reliable these were (what are the potential threats to accuracy/validity).

[B1] "Were there metrics of data quality available from the older mortality data?"

I did a bit of research now. I think B1 refers mostly to death registration completeness in vital statistics. 

In theory, there would be such metrics to tackle this. Here is a good summary on the methods used in this field for modern data:
https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0197047&type=printable 

However, again, looots of assumptions are included in these methods, and they are not really designed to assess long-term series which include demographic change. (I hope you agree on this??)

So, unless we find a method which is easy to calculate and suitable for long-term series (I will ask some other historical demographers, I already got feedback from Oxford and Oslo) I propose that we rely on the very valuable background information sheets in HMD (links below) to tackle A4 and write a short paragraph about the general good quality and completeness, but also highlighting some issues mentioned in the sheets here:

https://www.mortality.org/hmd/ESP/InputDB/ESPcom.pdf
https://www.mortality.org/hmd/SWE/InputDB/SWEcom.pdf
https://www.mortality.org/hmd/CHE/InputDB/CHEcom.pdf

What do you think?

Best wishes

Kaspar

**Comment by kasparstaub** [comment]
There is even a R package on three methods for indirect estimation of death registration coverage (Generalized Growth Balance, Synthetic Extinct Generations, and a hybrid of the two).

https://github.com/timriffe/AdultCoverage

Not sure if that could be used in our context?

**Comment by kasparstaub** [comment]
Here is the answer from a colleague in Oxford:

"To start, I know an old demography book that assesses the completeness of death registration in most European countries from the 1940s onwards. I thought I had easy access to it. I don't, but I just requested a scan of the relevant chapter from my library. I should be able to send it to you tomorrow. I expect it to confirm that death registration in Switzerland, Spain, and Sweden were all (nearly) complete from at least the 1940s.

Prior to the 1940s, I have experience using indirect census-based methods to estimate registration completeness (see an R implementation at https://github.com/timriffe/AdultCoverage), but the methods I have used require that one can assume that there is no migration. That assumption will definitely not hold for Sweden for 1880-1920, and I would be surprised if it were reasonable for Spain and Switzerland over the same period. However, if you have migration flow data for each population, Bhat has a formulation that allows you to calculate registration completeness in an open population: https://www.jstor.org/stable/3092939

Two other recommendations for now: 1) think about what it would mean for your analysis if death registration completeness increased over the period of analysis, especially over 1880 to 1940, and 2) it would probably be useful for you to reach out to historical demographers with specialties in each of those populations."

I have done 2) already and contacted several people I know in Spain, Switzerland and Sweden. Update soon.

My impression at the moment: Maybe we can calculate something simple based on the above mentioned R-package (and assume a stable population without migration, which is not very close to reality). If we want to include migration as well, then it will be rather complicated (and another additional sub-paper) if we want to calculate something ourselves.

**Comment by RPanczak** [comment]
Thank you for chasing that - really informative!

My vote for solution of that goes to using 'secondary' sources ie. book mentioned above & documentation from HMD. 

Presenting dummified measures which none of us knows how to calculate properly at the moment is not going to strengthen any of our claims; rather - open new set of problems and (probably justified) criticism.

On the other hand, investing time into figuring out of methods to do it properly is well beyond the scope of this paper - IMHO. If you disagree with that I'm happy to follow but rather unwilling to invest coding&data mgmt time on that front so we would need to find a lead person to tackle that.

**Comment by marcelzwahlen** [comment]
Agree: I think we need to say that counts of deaths and total population in these countries is the most solid information at the time of 1880 onwards. Cause of death ore any finder info is much mure open to being of questionable "validity". If we can add some refernces on mandatory birth and death recording for the 3 countries that would be great. I know these exist for Switzerland.

**Comment by kasparstaub** [comment]
I also fully agree. Got some more emails from Historical Demographers in Switzerland, Spain and Sweden. Page-filling emails with lots of info and literature. I spare you with everything. Long story short: Such metrics would exist, but have probably never been calculated for these countries. We would be the first. A bottomless pit, many challenges if you want to do that properly. So: We refer to the qualitative literature. Will draft a section on this. Thanks!!!
