### ISSUE TITLE
Table 1 re:work

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality#105]
Improvements to Table 1

- [x] split 'base info' from excess estimates
- [x] excess estimates to Table 2
- [x] COVID deaths #98

**Comment by RPanczak** [comment]
Hi team
We had some discussions on how to split table 1 into sth meaningful.. that doesn't mix 'base' data with results.

What would you say for table 1 having now only this info: 

![image](https://user-images.githubusercontent.com/31648642/142451725-b6d1e8ef-8025-406f-a03c-ec136353f586.png)

And table 2 this info 

![image](https://user-images.githubusercontent.com/31648642/142451873-2dcf12f1-d51c-4037-b675-7637636196ed.png)

**Comment by marcelzwahlen** [comment]
Suggest to add in second part the absolute excess mortality rate per 100'000 (or per million) wit 95% CI

**Comment by RPanczak** [comment]
Thanks. Good idea 💪 

Sth like that?

![image](https://user-images.githubusercontent.com/31648642/142462563-f30bd709-7403-41fa-9fa1-69e5ebb61e36.png)

**Comment by marcelzwahlen** [comment]
yes - thank you
