### ISSUE TITLE
Highlighted pandemics on figures do not match tables

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality#110]
Hi @kasparstaub 

We have some more highlights on the figures than we have in tables.

That probably came from earlier, broader definition of pandemics we checked.

Do you want to keep them on figures? Does it make any sense for instance for narrative in the manus or sth else?

Or do we stick to big hitters as in tables

![image](https://user-images.githubusercontent.com/31648642/143465284-74ba31ad-c55f-46a4-b7e3-302773aa52d4.png)

**Comment by kasparstaub** [comment]
If possible, keep them? If figures get to noisy or so, could also be left away with no harm... "wischiwaschi"-answer, sorry! :-)

**Comment by RPanczak** [comment]
👍 ⚡
