### ISSUE TITLE
consider adding excess deaths counts to Figure 2 OR separate graph?

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality#115]

**Comment by RPanczak** [comment]
Hi @marcelzwahlen & @kasparstaub 

We talked about adding absolute count of deaths to Fig 2. Quick and dirty first output is like that. Before committing  to more time to fix it (probably needs a legend, maybe second axis? data are rescaled by dividing by 100 to fit nicely) can you tell me your opinions? Stays like that? Sth to modify? Or separate graph to appendix?

![image](https://user-images.githubusercontent.com/31648642/144252340-c1401d17-235d-4724-a037-151b4d32420d.png)

We also have this one in appendix which could be recycled and match the color/presentation scheme of Fig 1?

![image](https://user-images.githubusercontent.com/31648642/144252662-b28a7495-57cb-46ac-b5e5-444938bb2085.png)

**Comment by marcelzwahlen** [comment]
Agree - does the labelling of y-axis also to the violet difference line? I guess so  , I just want to be sure about it.

**Comment by RPanczak** [comment]
Labelling on Y axis is correct for both.
But numbers presented by purple line (monthly excess) had to be divided by 100 to fit.

**Comment by marcelzwahlen** [comment]
this means with a second y-axis scale - possibly on the right - to make this change of scale clear - sorry

**Comment by RPanczak** [comment]
Thanks. Might be doable. @jriou is working on it atm so let's wait - maybe he has better idea =)

**Comment by jriou** [comment]
Yes I had another idea -- not sure if it is better, you tell me!

I thought that the violet line should be on the same scale as the others, that is excess scaled by population. THen I put it as an area because it looks better I think, but maybe it's too busy?

![image](https://user-images.githubusercontent.com/16086845/144271479-80612ff3-4c33-4071-9a98-ba6a1d7d5b1b.png)

**Comment by kasparstaub** [comment]
Great! I don't think it is too busy! We just have to carefully explain in der figure legend what we show.
