### ISSUE TITLE
Appendix:  compare weekly <> monthly counts

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality#66]
Initial work done on BfS data to estimate 2020 was done in file [10.Rmd](https://github.com/RPanczak/ISPM_excess-mortality/blob/main/analyses/10_CH-weekly-monthly-regs.Rmd)

For new work:

1. Data: STMH ❓ 
2. Period: 2010+ ❔ 
3. Method: adapt sin/cos smoothers 📉 
4. Countries: all 3️⃣ 
5. Measure: yearly total from two methods?
6. Week to month transform: solution ❔

**Comment by RPanczak** [comment]
Hi @KaMatthes 

Would you please rerun the comparison you prepared?

Please work in the `update_annals` branch to get up to date data!

There were some data updates, we had to rework some broken stan code and also - I started cleaning the repository preparing it for final release and removing unused files.

Maybe along the way some datasets or variables changed or disappeared so I apologize in advance if sth doesn't run out of the box.

**Comment by KaMatthes** [comment]
Hi @RPanczak 

Sure, I ran it again. And I understand that you had to clean the folder and so on. But could you maybe help me to find the following files or tell me the files I should use instead:

population Switzerland:                 ch_pop_year.Rds
Popoulation Switzerland 2020:      px-x-0102020000_202.px
Population Spain:                           es_pop_year.Rds
Population Sweden:                       se_pop_year.Rds

And is this still the correct path to the "death" files? I want to be sure to use the correct one:
data/mortality_org/stmf_week.Rds
data/mortality_org/stmf_month.Rds

**Comment by RPanczak** [comment]
Hola. 

All the cleaned up population figures can be now grabbed from one file `deaths_monthly` (in `data` folder). Please use `Population_obs` variable.

Path to the STMF files is the one you mentioned and it will remain unchanged.

Many thanks for help 💪

**Comment by KaMatthes** [comment]
Hi @RPanczak

I have updated the weekly and monthly comparison (plot_appendix_week_month.pdf, 19_Comparison_week_month.html) in the update_annals branch . Please let me know if you need anything else.

**Comment by RPanczak** [comment]
Thank you @KaMatthes.
I had to once again rearange the things to deal with Reviewers' request in #94 
Should be all sorted for now =)
