### ISSUE TITLE
Spain 1900-1907?

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality#81]
Hi @kasparstaub 
Quick question
Monthly deaths in Spain that you transcribed are available from `1900`
But age distribution of pop and deaths is from `1908`
Do you want to extend the analysis (at the cost of hunting for older datasets)?
Or start everything at `1908`?

**Comment by RPanczak** [comment]
@kasparstaub ?

**Comment by kasparstaub** [comment]
Thanks for reminding... :-) I quickly checked via INE. 

- Vital statistics exist for the period 1900-1907, but apparently they do not contain age-specific information on deaths:
https://www.ine.es/inebaseweb/libros.do?tntp=205002#

- There are also statistical yearbooks, but the books 1900-1911 seem to be missing.
https://www.ine.es/inebaseweb/libros.do?tntp=25687

So it is still possible, of course, that such data would exist, but at the moment I would have no idea where to look for it. Would need more time for research. Should we start at 1908 in the meantime?

**Comment by RPanczak** [comment]
Many thanks 👍 
Would vote for starting in 1908 and closing issue 🚀
