### ISSUE TITLE
cleaner figure 2

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality#89]
Hi team,

@jriou had some ideas to clean the Fig 2 a bit. - below is old on top new at the bottom.

Advantage of this solution is removal of duplicated axes labels and titles.
Disadvantage - CHE has to go on top, if that is disadvantage. 

Should we change it?

![image](https://user-images.githubusercontent.com/31648642/128996889-0554a583-0c31-4c83-9dbe-22b696a21325.png)

![image](https://user-images.githubusercontent.com/31648642/128996994-13a9061b-a833-4ef6-8e56-accbf7563aa2.png)

**Comment by kasparstaub** [comment]
Happy to change it, thank's a lot to both of you! Should we change the order in the other figures as well?
