### ISSUE TITLE
B4: COVID deaths 

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality#98]
> [B4] 2. How many COVID deaths occurred in these countries during 2020? I feel that this is a critical piece that helps to explain the current pandemic. How many of the excess deaths were COVID vs. non-COVID. Based on WHO estimates for 2020 (10,000 COVID deaths in Sweden, 8,000 in Switzerland and 55,000 in Spain), there are actually fewer excess deaths than COVID deaths in Sweden and about the same number in Switzerland. How do the authors interpret this finding? This is important context about what excess deaths represent.  

Need to:
 - [ ] get a source of data (preferably one for all three countries)
 - [x] integrate that nicely into table1

**Comment by RPanczak** [comment]
Need to:
 - [ ] get a source of data (preferably one for all three countries)
 - [ ] integrate that nicely into table1

**Comment by RPanczak** [comment]
Can automate data for that from 

>   Guidotti, E., Ardia, D., (2020), "COVID-19 Data Hub",
  Journal of Open Source Software 5(51):2376, doi:
  10.21105/joss.02376.

Do the numbers look reasonable @kasparstaub 

```
   Year id       Country     confirmed deaths
  <dbl> <chr>    <chr>           <int>  <int>
1  2020 2f37bf69 Spain         1928265  50837
2  2020 3e2d4144 Sweden         454758   9817
3  2020 ef51ecaa Switzerland    454239   7598
4  2021 2f37bf69 Spain         1893040  30046
5  2021 3e2d4144 Sweden         636096   4813
6  2021 ef51ecaa Switzerland    246131   2768
```

**Comment by kasparstaub** [comment]
In the Islam paper in BMJ the have the following numbers in Table 2

Sweden 8279
Switzerland 7210
Spain 49 824

(https://www.bmj.com/content/bmj/373/bmj.n1137.full.pdf)

In the legend they say: "Reported covid-19 deaths in 2020 (up to 27 December 2020, end of 52nd week). Source: Unified covid-19 dataset maintained by Johns Hopkins University Center for Systems Science and Engineering" 

Amazing how all these different numbers disagree. At least the magnitude is the same.

**Comment by RPanczak** [comment]
So it seems we have another 'source' drama 🙈 

Pulling data directly from JH ([here](https://coronavirus.jhu.edu/about/how-to-use-our-data) and [here](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data)) we get another set of numbers. Example for 2020:

```
  Country_Region Confirmed Deaths
  <chr>              <dbl>  <dbl>
1 Spain            1928265  50 837
2 Sweden            437379   8 727
3 Switzerland       452296   7 873
```

Spain:
RTVE: https://www.rtve.es/noticias/20200514/mapa-del-coronavirus-espana/2004681.shtml
Sweden:
The Swedish Public Health Agency: https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa
Switzerland:
Federal Office Of Public Health: https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/situation-schweiz-und-international.html
Open Government Data Reported By The Swiss Cantons: https://github.com/openZH/covid_19

Recommendations? Preferences? 
Pinging @marcelzwahlen

**Comment by jriou** [comment]
So the drama is that different sources give different counts of COVID deaths? I would just put a range and not bother too much :)

**Comment by marcelzwahlen** [comment]
I do not understand column number with 454239?
What is this? confirmed SARS-Cov2- infections? 

3  2020 ef51ecaa Switzerland    **454239**   7598

**Comment by RPanczak** [comment]
Yes I believe these are confirmed cases.

**Comment by marcelzwahlen** [comment]
Thank you 
we are only talking about the "official" covid deaths
If we list multiple sources, then I agree with Julien: let's put a range (which is not large)  on this.
More crucially: we need to discuss it - certainly by mentioning that lock-downs also had some indirect "benefits" in reducing deaths due to car accidents and in the winter 2020/2021 reducing mortality from seasonal influenza infection,

**Comment by RPanczak** [comment]
We decided to stick to JHU ftm
