### ISSUE TITLE
data updates

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_excess-mortality#99]
ageXsex deaths yearly:
 - [x] Spain 2019-21
 - [ ] ~Sweden 2021~ 💯 
 - [x] Switzerland 2021 🚀 

deaths monthly:
 - [x] Switzerland before 2020 🚀 
 - [x] Switzerland 2020 🚀 
 - [x] Switzerland 2021 🚀 
 - [ ] Spain before 2020 ❓ 
 - [ ] Spain 2020 
 - [x] Spain 2021
 - [ ] Sweden before 2020 ❓ 
 - [ ] Sweden 2020
 - [x] Sweden 2021

pops yearly:
 - [x] Spain 2020 
 - [x] Spain 2021

ageXsex pops:
 - [x] Spain 2020 
 - [x] Spain 2021

**Comment by RPanczak** [comment]
Hi @kasparstaub 

I chased some data updates but could use some help here
HMD is up to date now.
CHE updates have been resolved.
Also managed to quickly look at SWE for 2021 monthly data.

Would ou be able to check if any other datasets from INE or SCB had any updates that would be relevant to us?
I think getting age breakdown of 2021 deaths in 🇸🇪 would be the most super duper thing to have.
Thanks!

**Comment by kasparstaub** [comment]
Yes, I will have a look today! Thanks so much for solving all these other data issues!!!
